### ISSUE TITLE
Testing procedure

### ISSUE THREAD

**Issue by sushant21** [malllabiisc/HyTE#12]
While testing, it looks like the model only looks at the start time of an interval. Is that correct?

**Comment by ssdasgupta** [comment]
Yes, the model looks at the start time. Since we do not have any bias on the projection for any specific hyperplane, I assumed projecting to the start time suffice. You can also look at the average over all possible time hyperplanes, which makes it computationally expensive, might give a result with lower variance.

**Comment by richardcom** [comment]
Hi @ssdasgupta ! Sorry but I am a little confused. I thought in the model, for a fact such as `h, r, t, start_time, end_time`, it breaks up the period of time into different time bins during `load_data`. Thus, `h, r, t, start_time, end_time` is actually represented by `h, r, t, time1`, `h, r, t, time2`, `h, r, t, time3`, etc, where start_time < time1, time2, time3 < end_time. Thus, I fear that I might not have understood correctly, but may I double-check on which part of the model used only the start time of an interval?
